#!/usr/bin/perl

#use strict;

# build a hash of arrays
%myhash = ();

# populate with cities by state
#push(@{$myhash{"north dakota"}}, "fargo");
#push(@myhash{"north dakota"}, "west fargo");
#push(@myhash{"minnesota"}, "moorhead");
#push(@myhash{"minnesota"}, "dilworth");
@myhash{"north dakota"} = [ "fargo", "west fargo"];
@myhash{"minnesota"} = [ "dilworth", "moorhead"];

#$city = ${$myhash{"north dakota"}}[1];

## HTTP header
print "Content-type: text/html; charset=iso-8859-1\n\n";

## HTTP body

# html 
print "<html>\n";

# html head
print "<head>\n";

# dynamically create json objects for use in js.js
print "<script type=\"text/javascript\">\n";

# object
# geo[0] = { state : "name", cities : [ cities ]}

print "\tvar geo = [];\n";
for $state (keys %myhash)
{
	print "\tvar tmpstate = { state: \"$state\", cities: [] };\n";
	for $city (@{$myhash{$state}})
	{
		print "\ttmpstate.cities.push(\"$city\");\n";
	}
	print "\tgeo.push(tmpstate);\n";
}
print "</script>\n";

print "<script type=\"text/javascript\" src=\"/js.js\"></script>\n";

print "</head>\n";

# html body
print "<body>\n";

print "<script type=\"text/javascript\">\n";
print "document.getElementById(\"bob\").innerHTML = \"fred\";\n";
print "</script><br>\n";

# simple div
print "<p>\n";
print "<div id=\"bob\">hi!</div>\n";
print "<br>\n";
print "<br>\n";

# drop down #1, states (initially blank)
print "<select name=\"states\" id=\"states\" onchange=\"changeState()\">\n";

# loop through and load up states
print "\t<option value=\"none\" selected>choose state</option>\n";

for $state (keys %myhash)
{
	print "\t<option value=\"$state\">$state</option>\n";
}
print "</select>\n";
print "<br>\n";
print "<br>\n";

# drop down #2, cities (initially blank)
print "<select name=\"cities\" id=\"cities\">\n";
print "\t<option value=\"none\" selected>choose state</option>\n";
print "</select>\n";

print "</body>\n";

print "</html>\n";


exit(0);
