#!/usr/bin/python

print "Content-type: text/html; charset=iso-8859-1\n\n"

print "<html>"

print "<head>"
print "<title>my title</title>"
print "</head>"

print "<body>"

print "<h1>"
print "hello there"
print "</h1>"
print "</body>"

print "</html>"

exit(0)
