#!/bin/bash

echo "Content-type: text/plain; charset=iso-8859-1"
echo
echo
echo "testing\n"
echo "bob 1,2,3\n"
echo "\n"

for x in $(find / -type f -name 'python*' 2>/dev/null)
do
  echo "$x\n"
done

exit 0
